### ISSUE TITLE
Assign DOI to this repository

### ISSUE THREAD

**Issue by cosenal** [nathanieljohnston/QETLAB#10]
@nathanieljohnston It would be awesome if you could create a DOI for this repository. It should be very easy, just follow https://guides.github.com/activities/citable-code/

This way I could cite it properly in my thesis. I am pretty sure this needs to be done by the owner of the repository, otherwise I would have done it myself. Thanks!

**Comment by nathanieljohnston** [comment]
Whoops; I did that a little while ago actually, but forgot to actually put the DOI anywhere. Anyway:

http://dx.doi.org/10.5281/zenodo.14186

**Comment by cosenal** [comment]
Thanks! I added it to the readme file.
