### ISSUE TITLE
Tensor.m Base Case

### ISSUE THREAD

**Issue by vprusso** [nathanieljohnston/QETLAB#13]
Feel free to close this issue if my assumption here is wrong, but I believe in `Tensor.m`, if you create a vector say in the following way:

`q0 = [1;0];
Tensor(q0,0)
Tensor(q0,1)`

Then I would imagine that the first Tensor call would return a scalar or "1", while the second would return the vector "q0". The second call to the Tensor function works as expected, but the first also returns the vector "q0" as opposed to just "1". 

Again, if my intuition is incorrect here, please feel free to close this issue. Thanks!

**Comment by nathanieljohnston** [comment]
Thanks! I just uploaded a quick fix that makes the M = 0 base case return the scalar "1", as you suggested.
