### ISSUE TITLE
I could not run any comment on Online Matlab

### ISSUE THREAD

**Issue by apassenger** [nathanieljohnston/QETLAB#16]
Hello,
I just started to use qetlab but whtever I tried I always an error. For intance:
When I want to try that:

`GHZState(4,7,[1,2,3,4]/sqrt(30))`

I have this error: 
>  opt_args' is not found in the current folder or on the MATLAB path, but exists in:
>     /MATLAB Drive/QETLAB-0.9/helpers
> 
> Change the MATLAB current folder or add its folder to the MATLAB path.
> 
> Error in GHZState (line 36)
> [coeff] = opt_args({ ones(1,dim)/sqrt(dim) },varargin{:});

However When I try the same comment under the helper this time I have that:

> GHZState' is not found in the current folder or on the MATLAB path, but exists in:
>     /MATLAB Drive/QETLAB-0.9
>
> Change the MATLAB current folder or add its folder to the MATLAB path.

What I mean is that wherever I try I have an error

Or let's take a simple example:
`rho = RandomDensityMatrix(9);`
This time I have that:

> 'opt_args' is not found in the current folder or on the MATLAB path, but exists in:
>     /MATLAB Drive/QETLAB-0.9/helpers
> 
> Change the MATLAB current folder or add its folder to the MATLAB path.
> 
> Error in RandomDensityMatrix (line 33)
> [re,k,dist] = opt_args({ 0, dim, 'haar' },varargin{:});

**Comment by denisrosset** [comment]
Have you followed the installation instructions? http://www.qetlab.com/Installation

Then, both the main QETLAB folder and the helpers folder should be in your path, and everything should work correctly.

**Comment by apassenger** [comment]
It worked now 
I am using online matlab so I just forgat to delete helpers file after copying it in the qetlab folder

Thanks a lot
