### ISSUE TITLE
Error checking mismatch in `PermuteSystems`

### ISSUE THREAD

**Issue by vprusso** [nathanieljohnston/QETLAB#20]
Looks like the following line in `PermuteSystems.m`:
https://github.com/nathanieljohnston/QETLAB/blob/e4320f3f42eca70f21c5b8835b1076bdf586fa95/PermuteSystems.m#L62

Is checking for a different property than what is being stated in the comment below--that is, whether the length of `perm` and `dim` are equal. I think the correct fix here would be to alter the above line to:

```matlab
if length(dim) ~= num_sys
```

Obviously, this won't cause any correctness issue, but it may incorrectly flag an invalid input as valid or vice-versa.

**Comment by nathanieljohnston** [comment]
Fixed, thanks!
