### ISSUE TITLE
Block-positivity of block-positive operator appears to yield incorrect result

### ISSUE THREAD

**Issue by vprusso** [nathanieljohnston/QETLAB#21]
I'll start this issue off by saying there is a high likelihood that there is some form of user error on my part happening here. 

To give context, I am attempting to verify that the operators from Equation (35) in [arXiv:1408.6981](https://arxiv.org/pdf/1408.6981.pdf) are block-positive via QETLAB. 

The following is a script that attempts to verify the above fact. The equation reference numbers present in the arXiv:1408.6981 posting

```matlab
% Define variable epsilon \in [0,1] for resource state.
eps = 0.5;

% |0>, |1>.
e0 = [1;0]; e1 = [0;1];

% Define the standard two-qubit Bell states (Equation (2)).
psi_1 = [1/sqrt(2); 0; 0; 1/sqrt(2)]; 
psi_2 = [1/sqrt(2); 0; 0; -1/sqrt(2)];
psi_3 = [0; 1/sqrt(2); 1/sqrt(2); 0]; 
psi_4 = [0; 1/sqrt(2); -1/sqrt(2); 0];

% Define the corresponding density matrices of the Bell states.
rho_1 = psi_1 * psi_1'; rho_2 = psi_2 * psi_2';
rho_3 = psi_3 * psi_3'; rho_4 = psi_4 * psi_4';

% Define the resource state (Equation (18)):
eps_p = sqrt((1+eps)/2); eps_m = sqrt((1-eps)/2);
tau_vec = [eps_p; 0; 0; eps_m];
tau = tau_vec * tau_vec';

% Hermitian operator (Equation (32)).
H = 1/3 * (kron(eye(4), tau)/2 + ... 
    sqrt(1 - eps^2) * kron(rho_4, PartialTranspose(rho_4, 1, [2, 2])));

% Verify that the trace of H is equal to the closed-form expression (Equation (33)).
trace(H)
eq = 1/3 * (2 + sqrt(1-eps^2))

% Define Hermitian operators Q_{k,\eps} as in Equation (35) for k=1. 
% Should swap the second and third subsystems. 
% Each of the four subsystems is 2-dimensional.
Q0 = Swap(H - 1/3 * kron(rho_1, tau), [2, 3], [2, 2, 2, 2]);

% For k = 1,2,3, these operators should be block-positive however this 
% returns `0` which indicates that it is not determined to be block-positive.
IsBlockPositive(Q0)
```

I am *assuming* that perhaps the way in which I'm applying the `Swap` operator is perhaps not correct, although from my understanding I believe this is the correct way to go about doing this. 

This might be related as well, but for `eps=0.0` this appears to yield an `Inaccurate` state for the CVX solver. Could be related to my overall potential misunderstanding here as well though.

**Comment by nathanieljohnston** [comment]
Thanks for the report -- no user error on your part. That block positive matrix is right on the boundary of block positive matrices (i.e., if you minimize over product vectors, you get *exactly* zero), which makes it slightly tricky numerically. I had some numerical tolerance signs flipped. Fixed now. Now the following 3 lines of code yield results of -1, 1, and 0, respectively:

`IsBlockPositive(Q0)
IsBlockPositive(Q0+0.001*eye(16))
IsBlockPositive(Q0-0.001*eye(16))`

The first line yielding -1 (for "don't know") is a bit undesirable, but perhaps unavoidable: if the minimization over product states yields a value extremely close to 0, it's difficult to say with certainty whether or not it really is positive.

**Comment by vprusso** [comment]
@nathanieljohnston Thanks for the quick response! Glad to hear that there wasn't any user error on my part (this time, anyway :) ). And that explanation about the "don't know" case makes perfect sense. Thank you again for the quick response and fix!
